---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-web-srv-conf
  labels:
    app: web-srv
    release: web
data:
  ENV: PROD

---
apiVersion: v1
kind: Service
metadata:
  name: kube-web-srv
  labels:
    app: web-srv
    release: web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: web-srv
    release: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-web-srv
  labels:
    app: web-srv
    release: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-srv
      release: web
  template:
    metadata:
      labels:
        app: web-srv
        release: web
    spec:
      containers:
        - name: nginx
          image: "nginx:latest"
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10 
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
          - name: ENV
            valueFrom:
              configMapKeyRef:
                name: kube-web-srv-conf
                key: ENV
          resources:
            limits:
              cpu: "750m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kube-web-srv
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
